#!/bin/bash

# Tidy up
rm gifimgout*.jpg gifs in.gif in.gifv 2> /dev/null

# Download the reddit front page of /r/gifs
wget -O gifs --user-agent='linux:de.dompasch.asciigif:0.1 (by /u/sirerichbikendom)' https://www.reddit.com/r/gifs > /dev/null 2>&1
# Take a random imgur gifv link from the page
LINK=$(cat gifs | grep -oP "http:\S*?imgur\S*?.gifv" | sort -u | sort -R | head -1 | sed 's/gifv/webm/g')
# Download the gifv
wget -O in.gifv $LINK > /dev/null 2>&1

# File names
GIF=in.gif
VID=in.gifv
FRAMES=gifimgout%05d.jpg

# Split the gif / gifv into frames
if [ -f $VID ]; then
	ffmpeg -i $VID $FRAMES > /dev/null 2>&1
elif [ -f $GIF ]; then
	convert -coalesce $GIF $FRAMES > /dev/null 2>&1
fi

# Display each frame in ASCII, sleep, and clear the screen
for img in gifimgout*.jpg; do
	jp2a -f --grayscale $img 
	sleep 0.05
	clear
done

# Tidy up
rm gifimgout*.jpg gifs in.gif in.gifv 2> /dev/null
